# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05485e0c7795b8aa3e91d999db0c6e4d195c39fdb11dfb50b6a1f5d69f0295deccc58584d67795ab6466557b0f2b96fe819dd25f4730c9f82587cf152f8a7a55

test:
  secret_key_base: 238e5c8ae4ae8293c70edada110825dd3531caf71dad968e4c606284a3c3f2f431e079d339f66a3c7de220dbbd065ced8f1f69422051649899a00a8c2a35bf73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
